const fs = require('fs');
let c = fs.readFileSync('app/page.tsx', 'utf8');

// 1. Add "simulator" to tab type
c = c.replace(
  '"log" | "entries" | "csv" | "journal" | "leaderboard" | "focus" | "visual">("log")',
  '"log" | "entries" | "csv" | "journal" | "leaderboard" | "focus" | "visual" | "simulator">("log")'
);

// 2. Add nav entry
c = c.replace(
  '["visual",      "Visual Analysis" ],',
  '["visual",      "Visual Analysis" ],\n          ["simulator",   "Growth Simulator" ],'
);
c = c.replace(
  '["visual",      "Visual Analysis"  ],',
  '["visual",      "Visual Analysis"  ],\n          ["simulator",   "Growth Simulator"  ],'
);

// 3. Add render
c = c.replace(
  '{tab === "visual" && <VisualAnalysisTab entries={entries} />}',
  '{tab === "visual"     && <VisualAnalysisTab entries={entries} />}\n        {tab === "simulator"  && <GrowthSimulatorTab />}'
);
c = c.replace(
  '{tab === "visual"    && <VisualAnalysisTab entries={entries} />}',
  '{tab === "visual"     && <VisualAnalysisTab entries={entries} />}\n        {tab === "simulator"  && <GrowthSimulatorTab />}'
);

// 4. Skip if component already present
if (c.includes('GrowthSimulatorTab()')) {
  console.log('Component already present, skipping insertion');
} else {
  const component = [
    '',
    '// \u2500\u2500\u2500 Growth Simulator \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
    'function GrowthSimulatorTab() {',
    '  const [startBal, setStartBal]           = useState(50000);',
    '  const [tradesPerWeek, setTradesPerWeek] = useState(10);',
    '  const [winRate, setWinRate]             = useState(55);',
    '  const [rr, setRr]                       = useState(1.5);',
    '  const [riskPct, setRiskPct]             = useState(1);',
    '  const [riskCap, setRiskCap]             = useState(650);',
    '  const [monthlyWithdraw, setMonthlyWithdraw] = useState(4000);',
    '  const [chartMonths, setChartMonths]     = useState(24);',
    '  const canvasRef = useRef<HTMLCanvasElement>(null);',
    '  const riskFrac = riskPct / 100;',
    '  const wr       = winRate / 100;',
    '',
    '  function riskAmt(balance: number, frac: number, cap: number | null) {',
    '    const r = balance * frac;',
    '    return cap !== null ? Math.min(r, cap) : r;',
    '  }',
    '',
    '  function simulate(start: number, tpw: number, win: number, rratio: number, frac: number, withdraw: number, cap: number | null, months: number) {',
    '    let bal = start;',
    '    const balances = [bal];',
    '    const wrate = win / 100;',
    '    const tpm = Math.round(tpw * 4.33);',
    '    for (let m = 1; m <= months; m++) {',
    '      for (let t = 0; t < tpm; t++) {',
    '        const r = riskAmt(bal, frac, cap);',
    '        bal += Math.random() < wrate ? r * rratio : -r;',
    '        if (bal < 0) bal = 0;',
    '      }',
    '      bal -= withdraw;',
    '      if (bal < 0) bal = 0;',
    '      balances.push(bal);',
    '    }',
    '    return balances;',
    '  }',
    '',
    '  function avgSims(start: number, tpw: number, win: number, rratio: number, frac: number, withdraw: number, cap: number | null, months: number) {',
    '    const RUNS = 40;',
    '    const sums = Array(months + 1).fill(0);',
    '    for (let run = 0; run < RUNS; run++) {',
    '      simulate(start, tpw, win, rratio, frac, withdraw, cap, months).forEach((b, i) => { sums[i] += b; });',
    '    }',
    '    const balances = sums.map(s => s / RUNS);',
    '    const monthHit = balances.reduce((found: number | null, b, i) => found !== null ? found : (b >= 100000 && i > 0 ? i : null), null);',
    '    return { balances, monthHit };',
    '  }',
    '',
    '  const r            = riskAmt(startBal, riskFrac, riskCap);',
    '  const avgWin       = r * rr;',
    '  const avgLoss      = r;',
    '  const expectDollar = wr * avgWin - (1 - wr) * avgLoss;',
    '  const expectR      = wr * rr - (1 - wr);',
    '  const tpm          = Math.round(tradesPerWeek * 4.33);',
    '  const grossMonthly = expectDollar * tpm;',
    '  const netWeekly    = (grossMonthly - monthlyWithdraw) / 4.33;',
    '  const weeklyWithdraw = monthlyWithdraw / 4.33;',
    '  const capKicksBal  = riskCap / riskFrac;',
    '',
    '  const [cappedSim, setCappedSim]     = useState<{ balances: number[]; monthHit: number | null }>({ balances: [], monthHit: null });',
    '  const [uncappedSim, setUncappedSim] = useState<{ balances: number[]; monthHit: number | null }>({ balances: [], monthHit: null });',
    '',
    '  useEffect(() => {',
    '    const cap2 = avgSims(startBal, tradesPerWeek, winRate, rr, riskFrac, monthlyWithdraw, riskCap, chartMonths);',
    '    const unc2 = avgSims(startBal, tradesPerWeek, winRate, rr, riskFrac, monthlyWithdraw, null, chartMonths);',
    '    setCappedSim(cap2);',
    '    setUncappedSim(unc2);',
    '  }, [startBal, tradesPerWeek, winRate, rr, riskFrac, monthlyWithdraw, riskCap, chartMonths]);',
    '',
    '  useEffect(() => {',
    '    const canvas = canvasRef.current;',
    '    if (!canvas || cappedSim.balances.length === 0) return;',
    '    const ctx = canvas.getContext("2d");',
    '    if (!ctx) return;',
    '    const dpr = window.devicePixelRatio || 1;',
    '    const rect = canvas.getBoundingClientRect();',
    '    canvas.width  = rect.width  * dpr;',
    '    canvas.height = rect.height * dpr;',
    '    ctx.scale(dpr, dpr);',
    '    const W = rect.width, H = rect.height;',
    '    const ml = 72, mr = 78, mt = 16, mb = 36;',
    '    const cW = W - ml - mr, cH = H - mt - mb;',
    '    const months2 = cappedSim.balances.length - 1;',
    '    const cappedMax   = Math.max(...cappedSim.balances,   100000) * 1.12;',
    '    const uncappedMax = Math.max(...uncappedSim.balances, 100000) * 1.12;',
    '    const spData2 = chartMonths >= 60 ? Array.from({ length: months2 + 1 }, (_, i) => startBal * Math.pow(1.08, i / 12)) : null;',
    '    const xc = (i: number) => ml + (i / months2) * cW;',
    '    const yL = (v: number) => mt + cH - (v / cappedMax)   * cH;',
    '    const yR = (v: number) => mt + cH - (v / uncappedMax) * cH;',
    '    ctx.clearRect(0, 0, W, H);',
    '    for (let i = 0; i <= 5; i++) {',
    '      const y = mt + (i / 5) * cH;',
    '      ctx.strokeStyle = "#2d2f45"; ctx.lineWidth = 1; ctx.setLineDash([]);',
    '      ctx.beginPath(); ctx.moveTo(ml, y); ctx.lineTo(W - mr, y); ctx.stroke();',
    '    }',
    '    ctx.fillStyle = "#34d399"; ctx.font = "11px system-ui,sans-serif"; ctx.textAlign = "right"; ctx.textBaseline = "middle";',
    '    for (let i = 0; i <= 5; i++) ctx.fillText(fmtK2(((5-i)/5)*cappedMax), ml-6, mt+(i/5)*cH);',
    '    ctx.fillStyle = "#60a5fa"; ctx.textAlign = "left";',
    '    for (let i = 0; i <= 5; i++) ctx.fillText(fmtK2(((5-i)/5)*uncappedMax), W-mr+6, mt+(i/5)*cH);',
    '    ctx.fillStyle = "#64748b"; ctx.textAlign = "center"; ctx.textBaseline = "alphabetic";',
    '    const xstep = months2 <= 24 ? 5 : 10;',
    '    for (let i = 0; i <= months2; i += xstep) ctx.fillText(i === 0 ? "Start" : `Mo ${i}`, xc(i), H-6);',
    '    ctx.strokeStyle = "#ef4444"; ctx.lineWidth = 1.5; ctx.setLineDash([6,4]);',
    '    ctx.beginPath(); ctx.moveTo(ml, yL(100000)); ctx.lineTo(W-mr, yL(100000)); ctx.stroke();',
    '    if (spData2) {',
    '      ctx.strokeStyle = "#f59e0b"; ctx.lineWidth = 1.5; ctx.setLineDash([6,4]);',
    '      ctx.beginPath();',
    '      spData2.forEach((v,i) => i===0 ? ctx.moveTo(xc(i),yL(v)) : ctx.lineTo(xc(i),yL(v)));',
    '      ctx.stroke();',
    '    }',
    '    ctx.strokeStyle = "#60a5fa"; ctx.lineWidth = 2; ctx.setLineDash([8,4]);',
    '    ctx.beginPath();',
    '    uncappedSim.balances.forEach((v,i) => i===0 ? ctx.moveTo(xc(i),yR(v)) : ctx.lineTo(xc(i),yR(v)));',
    '    ctx.stroke();',
    '    ctx.setLineDash([]);',
    '    ctx.beginPath();',
    '    cappedSim.balances.forEach((v,i) => i===0 ? ctx.moveTo(xc(i),yL(v)) : ctx.lineTo(xc(i),yL(v)));',
    '    ctx.lineTo(xc(months2), mt+cH); ctx.lineTo(xc(0), mt+cH); ctx.closePath();',
    '    ctx.fillStyle = "rgba(52,211,153,0.12)"; ctx.fill();',
    '    ctx.strokeStyle = "#34d399"; ctx.lineWidth = 2.5; ctx.setLineDash([]);',
    '    ctx.beginPath();',
    '    cappedSim.balances.forEach((v,i) => i===0 ? ctx.moveTo(xc(i),yL(v)) : ctx.lineTo(xc(i),yL(v)));',
    '    ctx.stroke();',
    '  }, [cappedSim, uncappedSim, chartMonths, startBal]);',
    '',
    '  function fmtK2(v: number) {',
    '    if (v >= 1_000_000) return `$${(v/1_000_000).toFixed(1)}M`;',
    '    if (v >= 1_000)     return `$${Math.round(v/1000)}k`;',
    '    return `$${Math.round(v)}`;',
    '  }',
    '  function fmtD2(v: number) { return "$" + Math.round(v).toLocaleString(); }',
    '',
    '  const bal15 = cappedSim.balances[15] ?? 0;',
    '  const totalWithdrawn2 = chartMonths * monthlyWithdraw;',
    '',
    '  function SimSlider({ label, value, min, max, step, display, onChange }: {',
    '    label: string; value: number; min: number; max: number; step: number;',
    '    display: string; onChange: (v: number) => void;',
    '  }) {',
    '    return (',
    '      <div className="flex flex-col gap-1">',
    '        <span className="text-xs text-slate-400 uppercase tracking-wide">{label}</span>',
    '        <span className="text-lg font-semibold text-white">{display}</span>',
    '        <input type="range" min={min} max={max} step={step} value={value}',
    '          onChange={e => onChange(parseFloat(e.target.value))}',
    '          className="w-full accent-indigo-500 cursor-pointer" />',
    '      </div>',
    '    );',
    '  }',
    '',
    '  return (',
    '    <div className="space-y-5">',
    '      <div className="grid grid-cols-4 gap-x-6 gap-y-4">',
    '        <SimSlider label="Starting balance" value={startBal} min={10000} max={100000} step={1000} display={fmtD2(startBal)} onChange={setStartBal} />',
    '        <SimSlider label="Trades per week" value={tradesPerWeek} min={1} max={30} step={1} display={String(tradesPerWeek)} onChange={setTradesPerWeek} />',
    '        <SimSlider label="Win rate (%)" value={winRate} min={40} max={75} step={0.1} display={winRate.toFixed(1)+"%"} onChange={setWinRate} />',
    '        <SimSlider label="Avg R:R ratio" value={rr} min={1} max={4} step={0.01} display={rr.toFixed(2)} onChange={setRr} />',
    '        <SimSlider label="Risk per trade (%)" value={riskPct} min={0.001} max={3} step={0.001} display={riskPct.toFixed(3)+"%"} onChange={setRiskPct} />',
    '        <SimSlider label="Risk cap ($)" value={riskCap} min={50} max={2000} step={5} display={fmtD2(riskCap)} onChange={setRiskCap} />',
    '        <SimSlider label="Monthly withdrawal" value={monthlyWithdraw} min={0} max={8000} step={250} display={fmtD2(monthlyWithdraw)} onChange={setMonthlyWithdraw} />',
    '        <div className="flex flex-col gap-1">',
    '          <span className="text-xs text-slate-400 uppercase tracking-wide">Weekly withdrawal (auto)</span>',
    '          <span className="text-lg font-semibold text-slate-500">\u2248 {fmtD2(weeklyWithdraw)} / week</span>',
    '          <div className="w-full h-[18px]" />',
    '        </div>',
    '      </div>',
    '      <p className="text-xs text-slate-400">Risk scales until {fmtD2(capKicksBal)} \u2014 then locks at {fmtD2(riskCap)} per trade.</p>',
    '      <div className="grid grid-cols-6 gap-3">',
    '        {[',
    '          { label: "Month hit $100k\\n(capped)", main: cappedSim.monthHit !== null ? `Mo ${cappedSim.monthHit}` : "\u2014", sub: null, hl: null },',
    '          { label: "Balance at 15mo\\n(capped)", main: fmtD2(bal15), sub: null, hl: null },',
    '          { label: "Total withdrawn", main: fmtD2(totalWithdrawn2), sub: null, hl: null },',
    '          { label: "Avg win / trade", main: fmtD2(avgWin), sub: `Expect: ${fmtD2(expectDollar)}/trade`, hl: null },',
    '          { label: "Avg loss / trade", main: fmtD2(avgLoss), sub: `+${expectR.toFixed(3)}R expectancy`, hl: null },',
    '          { label: "Net weekly (start bal)", main: fmtD2(netWeekly), sub: `Gross mo: ${fmtD2(grossMonthly)}`, hl: netWeekly >= 0 ? "green" : "red" },',
    '        ].map((card, i) => (',
    '          <div key={i} className="bg-[#1e2035] rounded-lg p-3 border border-[#3d3f5e] flex flex-col gap-1">',
    '            <span className="text-xs text-slate-400 leading-tight whitespace-pre-line">{card.label}</span>',
    '            <span className={`text-xl font-bold ${card.hl === "green" ? "text-emerald-400" : card.hl === "red" ? "text-red-400" : "text-white"}`}>{card.main}</span>',
    '            {card.sub && <span className="text-xs text-slate-500">{card.sub}</span>}',
    '          </div>',
    '        ))}',
    '      </div>',
    '      <div className="flex items-center gap-2">',
    '        {([24, 60] as const).map(m => (',
    '          <button key={m} onClick={() => setChartMonths(m)}',
    '            className={`px-4 py-1.5 rounded-md text-sm font-medium border transition-all ${chartMonths === m ? "bg-[#2d2f45] border-slate-500 text-white" : "border-transparent text-slate-500 hover:text-slate-300"}`}>',
    '            {m === 24 ? "2 Years" : "5 Years"}',
    '          </button>',
    '        ))}',
    '      </div>',
    '      <div className="flex gap-5 text-xs text-slate-400 -mt-2">',
    '        <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-emerald-400 inline-block" />Capped (left axis)</span>',
    '        <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-sky-400 inline-block" />No cap (right axis)</span>',
    '        <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-red-500 inline-block" />$100k target</span>',
    '        {chartMonths >= 60 && <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-sm bg-amber-400 inline-block" />S&P 500 @ 8%/yr</span>}',
    '      </div>',
    '      <div className="w-full rounded-xl overflow-hidden border border-[#3d3f5e]" style={{ height: 380 }}>',
    '        <canvas ref={canvasRef} className="w-full h-full" style={{ display: "block" }} />',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
  ].join('\n');

  c = c.replace('// \u2500\u2500\u2500 Main Page', component + '// \u2500\u2500\u2500 Main Page');
}

fs.writeFileSync('app/page.tsx', c);
console.log('done - Growth Simulator added');
